In [1]:
print("hello world")

hello world


#### numpy 

```import numpy as np ```


```print("hello world")```

In [2]:
import numpy as np 

##### array:- collection of homogeneous data 

### creation of array 

In [3]:
# one dimensional array 
arr=np.array([1,2,3,4])
print(arr)
arr

[1 2 3 4]


array([1, 2, 3, 4])

In [4]:
# two dimensional array 
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [5]:
# three dimensional array 
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


#### mathematical functions on array 

In [6]:
# ones matrix 
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
# zeros matrix 
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# empty 
a=np.empty((2,2))
print(a)

[[0.00000000e+000 7.07564363e-312]
 [7.07564362e-312 7.07564363e-312]]


In [9]:
# arange 
a=np.arange(1,11,2)
print(a)

[1 3 5 7 9]


array information functions 

In [10]:
# shape 
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [11]:
# ndim 
print(arr2.ndim)
print(arr3.ndim)

2
3


In [12]:
# size 
print(arr2.size)

6


In [13]:
# dtype 
print(arr2.dtype)

int64


array reshaping functions 

In [14]:
# reshape 
# change the shape of array 
a=np.arange(12)
print(a)
b=a.reshape(3,4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
b
print(b.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


#### mathematical functions 

In [16]:
# sum()
a=np.array([10,20,30,40])
print(np.sum(a))

100


In [17]:
# min()
print(np.min(a))

10


In [18]:
# max()
print(np.max(a))

40


In [19]:
# mean()
print(np.mean(a))

25.0


In [20]:
# median()
print(np.median(a))

25.0


In [21]:
# std 
print(np.std(a))

11.180339887498949


In [22]:
# variance 
print(np.var(a))

125.0


#### arithmetics operations 

In [23]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[6,7]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 5  7]
 [ 9 11]]
[[-3 -3]
 [-3 -3]]
[[ 4 10]
 [18 28]]
[[0.25       0.4       ]
 [0.5        0.57142857]]


In [24]:
# random function 
a=np.random.rand(3)
print(a)

[0.68346999 0.52518047 0.17626575]


In [25]:
a=np.random.randint(3)
print(a)

1


sorting functions 

In [26]:
print(arr)

[1 2 3 4]


In [1]:
import numpy as np 

In [2]:
a=np.array([7,6,5,2,3,4,5,6,7,0,9,8,7,6])
print(np.sort(a))

[0 2 3 4 5 5 6 6 6 7 7 7 8 9]


In [4]:
arr2=np.array([[14,3,5],[6,5,8]])
print(arr2)

[[14  3  5]
 [ 6  5  8]]


In [5]:
print(np.sort(arr2))

[[ 3  5 14]
 [ 5  6  8]]


#### searching functions 


In [6]:
print(np.where(a==6))

(array([ 1,  7, 13]),)


unique values 

In [7]:
print(np.unique(a))

[0 2 3 4 5 6 7 8 9]


matrix functions 

In [8]:
# transpose 
print(arr2.T)

[[14  6]
 [ 3  5]
 [ 5  8]]


### matrix multiplication 

In [ ]:
# a=np.array([[1,2],[3,4]])
# b=np.array([[4,5],[6,7]])
# print(a)
# print(b)
# print(np.dot(a,b))

[[1 2]
 [3 4]]
[[4 5]
 [6 7]]
[[16 19]
 [36 43]]


In [21]:
a=np.array([1,2,3,4])
b=np.array([3,4,5])

In [16]:
print(np.concatenate((a,b)))

[1 2 3 3 4 5]


splitting array 

In [17]:
print(np.split(a,3))

[array([1]), array([2]), array([3])]


slicing

In [18]:
print(a[0:2])

[1 2]


In [19]:
print(np.sin(a))

[0.84147098 0.90929743 0.14112001]


In [22]:
print(np.log(a))

[0.         0.69314718 1.09861229 1.38629436]
